[package]
edition = "2021"
name = "kd_crawler"
version = "0.1.0"

[dependencies]
anyhow = {version = "1.0.34"}
chrono = {version = "0.4.19"}
reqwest = {version = "0.11", features = ["json"]}
select = {version = "0.5.0"}
tokio = {version = "1", features = ["full"]}
