[package]
edition = "2021"
name = "kd_crawler"
version = "0.1.0"

[dependencies]
chrono = {version = "0.4.19"}
reqwest = {version = "0.11", features = ["json"]}
tokio = {version = "1", features = ["full"]}
